#:kivy 1.11.1


<Members>:
    viewclass: 'Member'
    effect_cls: 'ScrollEffect'

    RecycleGridLayout:
        default_size: None, dp(35)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        cols: 1


<Member>:
    canvas:
        Color:
            rgba: 1, 1, 1, self.alpha
        Rectangle:
            size: self.size
            pos: self.pos
